/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIExample */

#ifndef _Included_JNIExample
#define _Included_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIExample
 * Method:    jniCrossInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNIExample_jniCrossInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNIExample
 * Method:    jniCross
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jstring JNICALL Java_JNIExample_jniCross
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
